/*
 * JCusparse - Java bindings for CUSPARSE, the NVIDIA CUDA sparse
 * matrix library, to be used with JCuda
 *
 * Copyright (c) 2010-2012 Marco Hutter - http://www.jcuda.org
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcuda_jcusparse_JCusparse */

#ifndef _Included_jcuda_jcusparse_JCusparse
#define _Included_jcuda_jcusparse_JCusparse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    setLogLevelNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jcuda_jcusparse_JCusparse_setLogLevelNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCreateNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCreateNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDestroyNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDestroyNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseGetVersionNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;[I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseGetVersionNative
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSetKernelStreamNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;Ljcuda/runtime/cudaStream_t;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSetKernelStreamNative
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCreateMatDescrNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCreateMatDescrNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDestroyMatDescrNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDestroyMatDescrNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSetMatTypeNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSetMatTypeNative
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseGetMatTypeNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseGetMatTypeNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSetMatFillModeNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSetMatFillModeNative
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseGetMatFillModeNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseGetMatFillModeNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSetMatDiagTypeNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSetMatDiagTypeNative
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseGetMatDiagTypeNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseGetMatDiagTypeNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSetMatIndexBaseNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSetMatIndexBaseNative
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseGetMatIndexBaseNative
 * Signature: (Ljcuda/jcusparse/cusparseMatDescr;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseGetMatIndexBaseNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCreateSolveAnalysisInfoNative
 * Signature: (Ljcuda/jcusparse/cusparseSolveAnalysisInfo;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCreateSolveAnalysisInfoNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDestroySolveAnalysisInfoNative
 * Signature: (Ljcuda/jcusparse/cusparseSolveAnalysisInfo;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDestroySolveAnalysisInfoNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSaxpyiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IFLjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSaxpyiNative
  (JNIEnv *, jclass, jobject, jint, jfloat, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDaxpyiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IDLjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDaxpyiNative
  (JNIEnv *, jclass, jobject, jint, jdouble, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCaxpyiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/cuComplex;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCaxpyiNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZaxpyiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/cuDoubleComplex;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZaxpyiNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSdotiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;[FI)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSdotiNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jfloatArray, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDdotiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;[DI)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDdotiNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jdoubleArray, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCdotiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/cuComplex;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCdotiNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZdotiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/cuDoubleComplex;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZdotiNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCdotciNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/cuComplex;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCdotciNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZdotciNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/cuDoubleComplex;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZdotciNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSgthrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSgthrNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDgthrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDgthrNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCgthrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCgthrNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZgthrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZgthrNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSgthrzNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSgthrzNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDgthrzNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDgthrzNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCgthrzNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCgthrzNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZgthrzNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZgthrzNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSsctrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSsctrNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDsctrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDsctrNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCsctrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCsctrNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZsctrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZsctrNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSrotiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;FFI)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSrotiNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jfloat, jfloat, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDrotiNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;DDI)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDrotiNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jdouble, jdouble, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseScsrmvNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIIFLjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;FLjcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseScsrmvNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jfloat, jobject, jobject, jobject, jobject, jobject, jfloat, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDcsrmvNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIIDLjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;DLjcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDcsrmvNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jdouble, jobject, jobject, jobject, jobject, jobject, jdouble, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCcsrmvNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIILjcuda/cuComplex;Ljcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/cuComplex;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCcsrmvNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZcsrmvNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIILjcuda/cuDoubleComplex;Ljcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/cuDoubleComplex;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZcsrmvNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseScsrsv_analysisNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcusparse/cusparseSolveAnalysisInfo;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseScsrsv_1analysisNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDcsrsv_analysisNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcusparse/cusparseSolveAnalysisInfo;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDcsrsv_1analysisNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCcsrsv_analysisNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcusparse/cusparseSolveAnalysisInfo;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCcsrsv_1analysisNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZcsrsv_analysisNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcusparse/cusparseSolveAnalysisInfo;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZcsrsv_1analysisNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseScsrsv_solveNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIFLjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcusparse/cusparseSolveAnalysisInfo;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseScsrsv_1solveNative
  (JNIEnv *, jclass, jobject, jint, jint, jfloat, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDcsrsv_solveNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIDLjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcusparse/cusparseSolveAnalysisInfo;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDcsrsv_1solveNative
  (JNIEnv *, jclass, jobject, jint, jint, jdouble, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCcsrsv_solveNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/cuComplex;Ljcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcusparse/cusparseSolveAnalysisInfo;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCcsrsv_1solveNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZcsrsv_solveNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/cuDoubleComplex;Ljcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcusparse/cusparseSolveAnalysisInfo;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZcsrsv_1solveNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseScsrmmNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIIIFLjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;IFLjcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseScsrmmNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jfloat, jobject, jobject, jobject, jobject, jobject, jint, jfloat, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDcsrmmNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIIIDLjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;IDLjcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDcsrmmNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jdouble, jobject, jobject, jobject, jobject, jobject, jint, jdouble, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCcsrmmNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIIILjcuda/cuComplex;Ljcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;ILjcuda/cuComplex;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCcsrmmNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jint, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZcsrmmNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIIILjcuda/cuDoubleComplex;Ljcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;ILjcuda/cuDoubleComplex;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZcsrmmNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jint, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSnnzNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSnnzNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDnnzNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDnnzNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCnnzNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCnnzNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZnnzNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IIILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZnnzNative
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSdense2csrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSdense2csrNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDdense2csrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDdense2csrNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCdense2csrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCdense2csrNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZdense2csrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZdense2csrNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseScsr2denseNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseScsr2denseNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDcsr2denseNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDcsr2denseNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCcsr2denseNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCcsr2denseNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZcsr2denseNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZcsr2denseNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseSdense2cscNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSdense2cscNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDdense2cscNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDdense2cscNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCdense2cscNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCdense2cscNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZdense2cscNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZdense2cscNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseScsc2denseNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseScsc2denseNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDcsc2denseNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDcsc2denseNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCcsc2denseNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCcsc2denseNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZcsc2denseNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/jcusparse/cusparseMatDescr;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZcsc2denseNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseXcoo2csrNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;Ljcuda/Pointer;IILjcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseXcoo2csrNative
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseXcsr2cooNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;Ljcuda/Pointer;IILjcuda/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseXcsr2cooNative
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jobject, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseScsr2cscNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;II)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseScsr2cscNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseDcsr2cscNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;II)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseDcsr2cscNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseCcsr2cscNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;II)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseCcsr2cscNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     jcuda_jcusparse_JCusparse
 * Method:    cusparseZcsr2cscNative
 * Signature: (Ljcuda/jcusparse/cusparseHandle;IILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;II)I
 */
JNIEXPORT jint JNICALL Java_jcuda_jcusparse_JCusparse_cusparseZcsr2cscNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
